### ISSUE TITLE
call to token-factory fails on `npm run start`

### ISSUE THREAD

**Issue by NithinBiliya** [onfido/onfido-sdk-web-sample-app#76]
I followed the readme. Cloned the repo, `npm install`, `npm run start` and went to `https://localhost:8090/`.

Nothing loads up. The network call to GET https://token-factory.onfido.com/sdk_token has failed.

Where to get the SDK_TOKEN_FACTORY_SECRET value to set as the env variable?

**Comment by kopijunkie** [comment]
Hi @NithinBiliya 

Please refer to the JS SDK repo's [Getting Started](https://github.com/onfido/onfido-sdk-ui#getting-started) section for guidance on setting up an integration and generating an SDK token. The SDK token factory is actually intended for internal use by Onfido developers.

Feel free to raise an issue there if you're experiencing any issues with your integration and we'll be happy to assist.

**Comment by NithinBiliya** [comment]
thanks @kopijunkie
