### ISSUE TITLE
"'NODE_ENV' is not recognized" on windows

### ISSUE THREAD

**Issue by genne** [onfido/onfido-sdk-web-sample-app#86]
This line doesn't fly on windows:

https://github.com/onfido/onfido-sdk-web-sample-app/blob/master/package.json#L8
```
"build": "NODE_ENV=production webpack -p --progress",
```

When running I get this error:
```
~\Documents\GitHub\onfido-sdk-web-sample-app [master ≡]> npm run start

> onfido-sdk-ui-app@0.0.2 prestart C:\Users\christian\Documents\GitHub\onfido-sdk-web-sample-app
> npm run build


> NODE_ENV=production webpack -p --progress

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onfido-sdk-ui-app@0.0.2 build: `NODE_ENV=production webpack -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the onfido-sdk-ui-app@0.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\christian\AppData\Roaming\npm-cache\_logs\2020-11-11T09_46_21_019Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onfido-sdk-ui-app@0.0.2 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the onfido-sdk-ui-app@0.0.2 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\christian\AppData\Roaming\npm-cache\_logs\2020-11-11T09_46_21_067Z-debug.log
```

(removing `NODE_ENV=production` works though)

**Comment by ethan605** [comment]
Hi @genne, thanks for using Onfido Web SDK.

On Windows, you need to use the separate command `set NODE_ENV=production` to set the environment variable. I recommend you to directly modify the `build` script in `package.json` into: `set NODE_ENV=production & webpack -p --progress `

Also, remember to set `SDK_TOKEN_FACTORY_SECRET` in [environment variables settings](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0)

**Comment by genne** [comment]
Yes, I got it to run. Just thought the documentation should be updated to reflect this?
